conf.py:
  copyright: 2010-2015
  project: TypoScript Service for Calendar Base
  version: 2.0
  release: 2.0.0
  latex_documents:
  - - Index
    - cal_ts_service.tex
    - TypoScript Service for Calendar Base
    - Mario Matzulla
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}